/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.java.ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rajmehta
 */
public class BrokerPanel extends javax.swing.JPanel {

    /**
     * Creates new form BrokerPanel
     */
    
    int loginId = 0;
    String loginName = "";
    String loginRegion = "";
    double loginCommrate = 0;
    String fundsType = "";
    double loginBalance = 0;
    double convertedFunds;
    String loginPass;
    
    public BrokerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPage_ui = new javax.swing.JPanel();
        id_brokerLogin_ui = new javax.swing.JTextField();
        pass_brokerLogin_ui = new javax.swing.JTextField();
        login_ui = new javax.swing.JButton();
        signin_ui = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        signinPage_ui = new javax.swing.JPanel();
        name_brokerSignin_ui = new javax.swing.JTextField();
        pass_brokerSignin_ui = new javax.swing.JTextField();
        regionSignin_ui = new javax.swing.JComboBox<>();
        signinSignin_ui = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        backSignin_ui = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        commrate_brokerSignup_ui = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        pass_brokerLogin_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_brokerLogin_uiActionPerformed(evt);
            }
        });

        login_ui.setText("Sign In");
        login_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_uiActionPerformed(evt);
            }
        });

        signin_ui.setText("Sign Up");
        signin_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_uiActionPerformed(evt);
            }
        });

        jLabel1.setText("Id:");

        jLabel2.setText("Password:");

        javax.swing.GroupLayout loginPage_uiLayout = new javax.swing.GroupLayout(loginPage_ui);
        loginPage_ui.setLayout(loginPage_uiLayout);
        loginPage_uiLayout.setHorizontalGroup(
            loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPage_uiLayout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addGroup(loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pass_brokerLogin_ui)
                    .addGroup(loginPage_uiLayout.createSequentialGroup()
                        .addComponent(login_ui)
                        .addGap(18, 18, 18)
                        .addComponent(signin_ui))
                    .addComponent(id_brokerLogin_ui))
                .addContainerGap(431, Short.MAX_VALUE))
        );
        loginPage_uiLayout.setVerticalGroup(
            loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPage_uiLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_brokerLogin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_brokerLogin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_ui)
                    .addComponent(signin_ui))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        add(loginPage_ui, "card2");

        regionSignin_ui.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIA", "USA", "BOSTON" }));

        signinSignin_ui.setText("Sign Up");
        signinSignin_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinSignin_uiActionPerformed(evt);
            }
        });

        jLabel3.setText("Name:");

        jLabel4.setText("Password:");

        jLabel5.setText("Region:");

        backSignin_ui.setText("Back");
        backSignin_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backSignin_uiActionPerformed(evt);
            }
        });

        jLabel6.setText("Commission Rate:");

        javax.swing.GroupLayout signinPage_uiLayout = new javax.swing.GroupLayout(signinPage_ui);
        signinPage_ui.setLayout(signinPage_uiLayout);
        signinPage_uiLayout.setHorizontalGroup(
            signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signinPage_uiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backSignin_ui)
                .addGap(31, 31, 31))
            .addGroup(signinPage_uiLayout.createSequentialGroup()
                .addGap(0, 332, Short.MAX_VALUE)
                .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(signinSignin_ui)
                    .addComponent(regionSignin_ui, javax.swing.GroupLayout.Alignment.TRAILING, 0, 170, Short.MAX_VALUE)
                    .addComponent(name_brokerSignin_ui, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pass_brokerSignin_ui, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(commrate_brokerSignup_ui))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        signinPage_uiLayout.setVerticalGroup(
            signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signinPage_uiLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_brokerSignin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_brokerSignin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regionSignin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(commrate_brokerSignup_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(signinSignin_ui)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(backSignin_ui)
                .addGap(16, 16, 16))
        );

        add(signinPage_ui, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void pass_brokerLogin_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_brokerLogin_uiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_brokerLogin_uiActionPerformed

    private void login_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_uiActionPerformed
        // TODO add your handling code here:
        try
        {
            Connection con = null;
            PreparedStatement p = null;
            ResultSet rs = null;

            String url= "jdbc:mysql://127.0.0.1:3306/stockdb"; // table details
            String username = "root"; // MySQL credentials
            String password = "root123$";

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url, username, password);

            if (con != null)
            {
                System.out.println("Connected to the database StockDB");

                String sql = "Select * from broker where brokerid="+Integer.parseInt(id_brokerLogin_ui.getText())+" AND password= '"+String.valueOf(pass_brokerLogin_ui.getText())+"';";
                p = con.prepareStatement(sql);
                rs = p.executeQuery();

                boolean login = false;
                while (rs.next())
                {
                    loginId = rs.getInt("brokerid");
                    loginName =rs.getString("name");
                    loginRegion = rs.getString("region");
                    loginCommrate = rs.getDouble("commissionrate");

                    login = true;
                    JOptionPane.showMessageDialog(this,"Login successful for "+loginId+ " Name: "+loginName);
                    loginPage_ui.setVisible(false);

                }

                if(!login){JOptionPane.showMessageDialog(this,"Enter Valid details");}

            }
        }
        catch (SQLException ex)
        {
            // handle any errors
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_login_uiActionPerformed

    private void signin_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin_uiActionPerformed
        // TODO add your handling code here:
        loginPage_ui.setVisible(false);
        signinPage_ui.setVisible(true);
    }//GEN-LAST:event_signin_uiActionPerformed

    private void signinSignin_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinSignin_uiActionPerformed
        // TODO add your handling code here:

        String fundsType = "";

        try
        {
            Connection con = null;
            PreparedStatement p = null;
            ResultSet rs = null;

            String url= "jdbc:mysql://127.0.0.1:3306/stockdb"; // table details
            String username = "root"; // MySQL credentials
            String password = "root123$";

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url, username, password);

            if (con != null)
            {
                System.out.println("Connected to the database StockDB");

                String sql = "INSERT INTO broker (name, region, commission, commissionrate, password) VALUES ('"+String.valueOf(name_brokerSignin_ui.getText())+"','"+String.valueOf(regionSignin_ui.getSelectedItem())+"',0,'"+String.valueOf(commrate_brokerSignup_ui.getText())+"','"+String.valueOf(pass_brokerSignin_ui.getText())+"');";

                p = con.prepareStatement(sql);
                int rowDeleted = p.executeUpdate();
                if(rowDeleted > 0){
                    String fetchId = "select * from broker where password = '" +String.valueOf(pass_brokerSignin_ui.getText())+"' AND name = '"+String.valueOf(name_brokerSignin_ui.getText())+"';";
                    p = con.prepareStatement(fetchId);
                    rs = p.executeQuery();

                    int id =0;

                    while (rs.next())
                    {
                        id = rs.getInt("brokerid");
                    }
                    JOptionPane.showMessageDialog(this,"Account Created with id: "+id );
                }

            }
        }
        catch (SQLException ex)
        {
            // handle any errors
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_signinSignin_uiActionPerformed

    private void backSignin_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backSignin_uiActionPerformed
        // TODO add your handling code here:
        signinPage_ui.setVisible(false);
        loginPage_ui.setVisible(true);
    }//GEN-LAST:event_backSignin_uiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backSignin_ui;
    private javax.swing.JTextField commrate_brokerSignup_ui;
    private javax.swing.JTextField id_brokerLogin_ui;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel loginPage_ui;
    private javax.swing.JButton login_ui;
    private javax.swing.JTextField name_brokerSignin_ui;
    private javax.swing.JTextField pass_brokerLogin_ui;
    private javax.swing.JTextField pass_brokerSignin_ui;
    private javax.swing.JComboBox<String> regionSignin_ui;
    private javax.swing.JPanel signinPage_ui;
    private javax.swing.JButton signinSignin_ui;
    private javax.swing.JButton signin_ui;
    // End of variables declaration//GEN-END:variables
}
