/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.java.ui;

import com.java.Faker.Parser;
import com.java.broker.BrokerHandler;
import com.java.profile.Profile;
import com.java.transaction.TransactionHandler;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rajmehta
 */
public class BrokerPanel extends javax.swing.JPanel {

    /**
     * Creates new form BrokerPanel
     */
    private static final DecimalFormat df = new DecimalFormat("0.000");
    int loginId = 0;
    String loginName = "";
    String loginRegion = "";
    double loginCommrate = 0;
    String fundsType = "";
    double loginBalance = 0;
    double convertedFunds;
    String loginPass;
    BrokerHandler brokhandobj = new BrokerHandler();
    DefaultTableModel brokerClients;
    DefaultTableModel transactionTable;
    TransactionHandler thobj = new TransactionHandler();
    
    int transactionid_db;
    int brokerid_db;
    int profileid_db;
    int qty_db;
    String type_db;
    double stockprice_db;
    double transactiontotal_db;
    String stocktag_db;
    double commission_db;
    String transactiondate_db;
    String action_db;
    
    public BrokerPanel() {
        initComponents();
        brokerClients = (DefaultTableModel) brokerClients_ui.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        loginPage_ui = new javax.swing.JPanel();
        id_brokerLogin_ui = new javax.swing.JTextField();
        pass_brokerLogin_ui = new javax.swing.JTextField();
        login_ui = new javax.swing.JButton();
        signin_ui = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        back1 = new javax.swing.JButton();
        signinPage_ui = new javax.swing.JPanel();
        name_brokerSignin_ui = new javax.swing.JTextField();
        pass_brokerSignin_ui = new javax.swing.JTextField();
        regionSignin_ui = new javax.swing.JComboBox<>();
        signinSignin_ui = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        backSignin_ui = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        commrate_brokerSignup_ui = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        MainBrokerPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        brokerName_ui = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        totalCommUSD_ui = new javax.swing.JTextField();
        totalCommINR_ui = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        brokerClients_ui = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        transactionReq_ui = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        commRate_ui = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TransactionRequestPanel_ui = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        transacionTable_ui = new javax.swing.JTable();
        aproveStock = new javax.swing.JButton();
        denyStock = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setLayout(new java.awt.CardLayout());

        loginPage_ui.setBackground(new java.awt.Color(43, 63, 87));

        id_brokerLogin_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N

        pass_brokerLogin_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        pass_brokerLogin_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_brokerLogin_uiActionPerformed(evt);
            }
        });

        login_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        login_ui.setText("Sign In");
        login_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_uiActionPerformed(evt);
            }
        });

        signin_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        signin_ui.setText("Sign Up");
        signin_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_uiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("BROKER'S LOGIN");

        back1.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        back1.setText("Back to Login");
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPage_uiLayout = new javax.swing.GroupLayout(loginPage_ui);
        loginPage_ui.setLayout(loginPage_uiLayout);
        loginPage_uiLayout.setHorizontalGroup(
            loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPage_uiLayout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addGroup(loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(login_ui))
                .addGroup(loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPage_uiLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pass_brokerLogin_ui)
                            .addComponent(id_brokerLogin_ui)))
                    .addGroup(loginPage_uiLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(signin_ui)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPage_uiLayout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addGroup(loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPage_uiLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(360, 360, 360))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPage_uiLayout.createSequentialGroup()
                        .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))))
        );

        loginPage_uiLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {back1, id_brokerLogin_ui, jLabel1, jLabel2, login_ui, pass_brokerLogin_ui, signin_ui});

        loginPage_uiLayout.setVerticalGroup(
            loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPage_uiLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_brokerLogin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_brokerLogin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_ui)
                    .addComponent(signin_ui))
                .addGap(149, 149, 149)
                .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        add(loginPage_ui, "card2");

        signinPage_ui.setBackground(new java.awt.Color(43, 63, 87));

        name_brokerSignin_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N

        pass_brokerSignin_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N

        regionSignin_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        regionSignin_ui.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIA", "USA", "BOSTON" }));

        signinSignin_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        signinSignin_ui.setText("Sign Up");
        signinSignin_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinSignin_uiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Region:");

        backSignin_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        backSignin_ui.setText("Back");
        backSignin_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backSignin_uiActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Commission Rate:");

        commrate_brokerSignup_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("SIGN UP PAGE");

        javax.swing.GroupLayout signinPage_uiLayout = new javax.swing.GroupLayout(signinPage_ui);
        signinPage_ui.setLayout(signinPage_uiLayout);
        signinPage_uiLayout.setHorizontalGroup(
            signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signinPage_uiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backSignin_ui)
                .addGap(31, 31, 31))
            .addGroup(signinPage_uiLayout.createSequentialGroup()
                .addGap(0, 313, Short.MAX_VALUE)
                .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signinPage_uiLayout.createSequentialGroup()
                        .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(signinSignin_ui)
                            .addComponent(regionSignin_ui, javax.swing.GroupLayout.Alignment.TRAILING, 0, 170, Short.MAX_VALUE)
                            .addComponent(name_brokerSignin_ui, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pass_brokerSignin_ui, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(commrate_brokerSignup_ui)))
                    .addGroup(signinPage_uiLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        signinPage_uiLayout.setVerticalGroup(
            signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signinPage_uiLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_brokerSignin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_brokerSignin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regionSignin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(commrate_brokerSignup_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(signinSignin_ui)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(backSignin_ui)
                .addGap(16, 16, 16))
        );

        add(signinPage_ui, "card3");

        MainBrokerPanel.setBackground(new java.awt.Color(43, 63, 87));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Broker Panel");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Welcome Back:");

        brokerName_ui.setEditable(false);
        brokerName_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Commission");

        totalCommUSD_ui.setEditable(false);
        totalCommUSD_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        totalCommUSD_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalCommUSD_uiActionPerformed(evt);
            }
        });

        totalCommINR_ui.setEditable(false);
        totalCommINR_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("USD");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("INR");

        brokerClients_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        brokerClients_ui.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ProfileId", "Name", "Type"
            }
        ));
        jScrollPane1.setViewportView(brokerClients_ui);

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("My Clients");

        transactionReq_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        transactionReq_ui.setText("Transaction Requests");
        transactionReq_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionReq_uiActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("My Commission Rate:");

        commRate_ui.setEditable(false);
        commRate_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        commRate_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commRate_uiActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("%");

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainBrokerPanelLayout = new javax.swing.GroupLayout(MainBrokerPanel);
        MainBrokerPanel.setLayout(MainBrokerPanelLayout);
        MainBrokerPanelLayout.setHorizontalGroup(
            MainBrokerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainBrokerPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(MainBrokerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(MainBrokerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brokerName_ui, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(commRate_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MainBrokerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalCommUSD_ui, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalCommINR_ui, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainBrokerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainBrokerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainBrokerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainBrokerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(344, 344, 344))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainBrokerPanelLayout.createSequentialGroup()
                        .addComponent(transactionReq_ui)
                        .addGap(394, 394, 394))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainBrokerPanelLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainBrokerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(396, 396, 396))))
        );
        MainBrokerPanelLayout.setVerticalGroup(
            MainBrokerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainBrokerPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addGroup(MainBrokerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainBrokerPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(MainBrokerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(brokerName_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(commRate_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(MainBrokerPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(MainBrokerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(totalCommUSD_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainBrokerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalCommINR_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(transactionReq_ui)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(MainBrokerPanel, "card4");

        TransactionRequestPanel_ui.setBackground(new java.awt.Color(43, 63, 87));

        transacionTable_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        transacionTable_ui.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "transactionId", "brokerId", "profileId", "qty", "Type", "stockprice", "transtotal", "stocktag", "commission", "date", "action"
            }
        ));
        jScrollPane2.setViewportView(transacionTable_ui);

        aproveStock.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        aproveStock.setText("Approve");
        aproveStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aproveStockActionPerformed(evt);
            }
        });

        denyStock.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        denyStock.setText("Deny");
        denyStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denyStockActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("CUSTOMER TRANSACTION REQUESTS");

        back.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TransactionRequestPanel_uiLayout = new javax.swing.GroupLayout(TransactionRequestPanel_ui);
        TransactionRequestPanel_ui.setLayout(TransactionRequestPanel_uiLayout);
        TransactionRequestPanel_uiLayout.setHorizontalGroup(
            TransactionRequestPanel_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransactionRequestPanel_uiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TransactionRequestPanel_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(TransactionRequestPanel_uiLayout.createSequentialGroup()
                        .addComponent(aproveStock, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(denyStock, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(TransactionRequestPanel_uiLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TransactionRequestPanel_uiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(14, 14, 14))
        );
        TransactionRequestPanel_uiLayout.setVerticalGroup(
            TransactionRequestPanel_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TransactionRequestPanel_uiLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(TransactionRequestPanel_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aproveStock)
                    .addComponent(denyStock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(14, 14, 14))
        );

        add(TransactionRequestPanel_ui, "card5");
    }// </editor-fold>//GEN-END:initComponents

    private void pass_brokerLogin_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_brokerLogin_uiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_brokerLogin_uiActionPerformed

    private void login_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_uiActionPerformed
        // TODO add your handling code here:
        Parser parser = new Parser();
        boolean flag = parser.isInteger(id_brokerLogin_ui.getText());
        if(id_brokerLogin_ui.getText().isEmpty() || pass_brokerLogin_ui.getText().isEmpty()){flag = false;}
        if(flag){
        try
        {
            Connection con = null;
            PreparedStatement p = null;
            ResultSet rs = null;

            String url= "jdbc:mysql://127.0.0.1:3306/stockdb"; // table details
            String username = "root"; // MySQL credentials
            String password = "root123$";

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url, username, password);

            if (con != null)
            {
                System.out.println("Connected to the database StockDB");

                String sql = "Select * from broker where brokerid="+Integer.parseInt(id_brokerLogin_ui.getText())+" AND password= '"+String.valueOf(pass_brokerLogin_ui.getText())+"';";
                p = con.prepareStatement(sql);
                rs = p.executeQuery();

                boolean login = false;
                while (rs.next())
                {
                    loginId = rs.getInt("brokerid");
                    loginName =rs.getString("name");
                    loginRegion = rs.getString("region");
                    loginCommrate = rs.getDouble("commissionrate");

                    login = true;
                    JOptionPane.showMessageDialog(this,"Login successful for "+loginId+ " Name: "+loginName);
                    
                    loadBrokerPage();
                    loginPage_ui.setVisible(false);
                    MainBrokerPanel.setVisible(true);
                    
                    refreshTransactionRequest();

                }

                if(!login){JOptionPane.showMessageDialog(this,"Enter Valid details");}

            }
        }
        catch (SQLException ex)
        {
            // handle any errors
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else{JOptionPane.showMessageDialog(this, "Null or Type Mismatch");}
    }//GEN-LAST:event_login_uiActionPerformed

    private void signin_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin_uiActionPerformed
        // TODO add your handling code here:
        loginPage_ui.setVisible(false);
        signinPage_ui.setVisible(true);
    }//GEN-LAST:event_signin_uiActionPerformed

    private void signinSignin_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinSignin_uiActionPerformed
        // TODO add your handling code here:
        boolean flag2= true;
        if(name_brokerSignin_ui.getText().isEmpty() || pass_brokerSignin_ui.getText().isEmpty() || commrate_brokerSignup_ui.getText().isEmpty()){flag2 = false;}
        if(flag2){
        String fundsType = "";

        try
        {
            Connection con = null;
            PreparedStatement p = null;
            ResultSet rs = null;

            String url= "jdbc:mysql://127.0.0.1:3306/stockdb"; // table details
            String username = "root"; // MySQL credentials
            String password = "root123$";

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url, username, password);

            if (con != null)
            {
                System.out.println("Connected to the database StockDB");

                String sql = "INSERT INTO broker (name, region, commission, commissionrate, password) VALUES ('"+String.valueOf(name_brokerSignin_ui.getText())+"','"+String.valueOf(regionSignin_ui.getSelectedItem())+"',0,'"+String.valueOf(commrate_brokerSignup_ui.getText())+"','"+String.valueOf(pass_brokerSignin_ui.getText())+"');";

                p = con.prepareStatement(sql);
                int rowDeleted = p.executeUpdate();
                if(rowDeleted > 0){
                    String fetchId = "select * from broker where password = '" +String.valueOf(pass_brokerSignin_ui.getText())+"' AND name = '"+String.valueOf(name_brokerSignin_ui.getText())+"';";
                    p = con.prepareStatement(fetchId);
                    rs = p.executeQuery();

                    int id =0;

                    while (rs.next())
                    {
                        id = rs.getInt("brokerid");
                    }
                    JOptionPane.showMessageDialog(this,"Account Created with id: "+id );
                }

            }
        }
        catch (SQLException ex)
        {
            // handle any errors
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else{JOptionPane.showMessageDialog(this, "Null or Type Mismatch");}
    }//GEN-LAST:event_signinSignin_uiActionPerformed

    private void backSignin_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backSignin_uiActionPerformed
        // TODO add your handling code here:
        signinPage_ui.setVisible(false);
        loginPage_ui.setVisible(true);
    }//GEN-LAST:event_backSignin_uiActionPerformed

    private void totalCommUSD_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalCommUSD_uiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalCommUSD_uiActionPerformed

    private void transactionReq_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionReq_uiActionPerformed
        // TODO add your handling code here:
        TransactionRequestPanel_ui.setVisible(true);
        MainBrokerPanel.setVisible(false);
        loginPage_ui.setVisible(false);
    }//GEN-LAST:event_transactionReq_uiActionPerformed

    private void aproveStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aproveStockActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = transacionTable_ui.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to Approve/Reject");
            return;
        }
        else{
            transactionTable = (DefaultTableModel) transacionTable_ui.getModel();
            int tid = (Integer) transactionTable.getValueAt(selectedRowIndex, 0);
            brokerid_db = (Integer) transactionTable.getValueAt(selectedRowIndex, 1);
            profileid_db = (Integer) transactionTable.getValueAt(selectedRowIndex, 2);
            qty_db = (Integer) transactionTable.getValueAt(selectedRowIndex, 3);
            type_db = (String) transactionTable.getValueAt(selectedRowIndex, 4);
            stockprice_db = (Double) transactionTable.getValueAt(selectedRowIndex, 5);
            transactiontotal_db = (Double) transactionTable.getValueAt(selectedRowIndex, 6);
            stocktag_db = (String) transactionTable.getValueAt(selectedRowIndex, 7);
            commission_db = (Double) transactionTable.getValueAt(selectedRowIndex, 8);
            transactiondate_db = (String) transactionTable.getValueAt(selectedRowIndex, 9);
            action_db = (String) transactionTable.getValueAt(selectedRowIndex, 10);

            System.out.println("TransactionId is: "+tid);
            System.out.println("StockTag for approval is: "+stocktag_db);
            
            refreshTransactionRequest();

            try {
                thobj.ApproveStkReq(tid, transactiontotal_db, commission_db, profileid_db, type_db, qty_db, stocktag_db,loginId);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(BrokerPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_aproveStockActionPerformed

    private void commRate_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commRate_uiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commRate_uiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainBrokerPanel.setVisible(false);
        loginPage_ui.setVisible(true);
        try {
            loadBrokerPage();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BrokerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        // TODO add your handling code here:
        loginPage_ui.setVisible(false);
        MainPanel back1 = new MainPanel();
        back1.setVisible(true);
    }//GEN-LAST:event_back1ActionPerformed

    private void denyStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denyStockActionPerformed
        // TODO add your handling code here:
        refreshTransactionRequest();
    }//GEN-LAST:event_denyStockActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        try {
            // TODO add your handling code here:
            loadBrokerPage();
            TransactionRequestPanel_ui.setVisible(false);
            MainBrokerPanel.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BrokerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backActionPerformed

    public void loadBrokerPage() throws ClassNotFoundException{
        brokerName_ui.setText(loginName);
        commRate_ui.setText(String.valueOf(loginCommrate));
        
        ArrayList<Profile> allProfiletoBrok = brokhandobj.viewAllProfileToBroker(loginId);
        Object[] rows = new Object[3];
        brokerClients.setRowCount(0);
        for(Profile p:allProfiletoBrok){
            rows[0]=p.getId();
            rows[1]=p.getName();
            rows[2]=p.getType();
            brokerClients.addRow(rows);
        }
        
        try 
        {
            Connection con = null;
            PreparedStatement p = null;
            ResultSet rs = null;

            String url= "jdbc:mysql://127.0.0.1:3306/stockdb"; // table details 
            String username = "root"; // MySQL credentials
            String password = "root123$";

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url, username, password);

            if (con != null) 
            {
                System.out.println("Connected to broker");

                String sql = "Select * from broker where brokerid="+loginId+";";
                System.out.println(sql);
                p = con.prepareStatement(sql);
                rs = p.executeQuery();
                Object[] row = new Object[11];
                    while (rs.next()) 
                    {   
                            if(rs.getString("region").equals("INDIA")){
                                totalCommINR_ui.setText(String.valueOf(df.format(rs.getDouble("commission"))));
                                totalCommUSD_ui.setText(String.valueOf(df.format(currencyconverter(rs.getDouble("commission"), "INDIA"))));
                            }
                            else{
                                totalCommUSD_ui.setText(String.valueOf(df.format(rs.getDouble("commission"))));
                                totalCommINR_ui.setText(String.valueOf(df.format(currencyconverter(rs.getDouble("commission"), "USA"))));
                            }  
                    }
            }
        } 
        catch (SQLException ex) 
        {
            // handle any errors
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void refreshTransactionRequest(){
        transactionTable = (DefaultTableModel) transacionTable_ui.getModel();
        transactionTable.setRowCount(0);
        try 
        {
            Connection con = null;
            PreparedStatement p = null;
            ResultSet rs = null;

            String url= "jdbc:mysql://127.0.0.1:3306/stockdb"; // table details 
            String username = "root"; // MySQL credentials
            String password = "root123$";

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url, username, password);

            if (con != null) 
            {
                System.out.println("Connected to the database StockDB");

                String sql = "Select * from transaction where brokerid="+loginId+" AND action ='PENDING';";
                System.out.println(sql);
                p = con.prepareStatement(sql);
                rs = p.executeQuery();
                Object[] row = new Object[11];
                    while (rs.next()) 
                    {   
                            row[0] = rs.getInt("transactionid");
                            row[1] = rs.getInt("brokerid");
                            row[2] = rs.getInt("profileid");
                            row[3] = rs.getInt("qty");
                            row[4] = rs.getString("type");
                            row[5] = rs.getDouble("stockprice");
                            row[6] = rs.getDouble("transactiontotal");
                            row[7] = rs.getString("stocktag");
                            row[8] = rs.getDouble("commission");
                            row[9] = rs.getString("transactiondate");
                            row[10] = rs.getString("action");                            
                            transactionTable.addRow(row);
                    }
            }
        } 
        catch (SQLException ex) 
        {
            // handle any errors
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainBrokerPanel;
    private javax.swing.JPanel TransactionRequestPanel_ui;
    private javax.swing.JButton aproveStock;
    private javax.swing.JButton back;
    private javax.swing.JButton back1;
    private javax.swing.JButton backSignin_ui;
    private javax.swing.JTable brokerClients_ui;
    private javax.swing.JTextField brokerName_ui;
    private javax.swing.JTextField commRate_ui;
    private javax.swing.JTextField commrate_brokerSignup_ui;
    private javax.swing.JButton denyStock;
    private javax.swing.JTextField id_brokerLogin_ui;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel loginPage_ui;
    private javax.swing.JButton login_ui;
    private javax.swing.JTextField name_brokerSignin_ui;
    private javax.swing.JTextField pass_brokerLogin_ui;
    private javax.swing.JTextField pass_brokerSignin_ui;
    private javax.swing.JComboBox<String> regionSignin_ui;
    private javax.swing.JPanel signinPage_ui;
    private javax.swing.JButton signinSignin_ui;
    private javax.swing.JButton signin_ui;
    private javax.swing.JTextField totalCommINR_ui;
    private javax.swing.JTextField totalCommUSD_ui;
    private javax.swing.JTable transacionTable_ui;
    private javax.swing.JToggleButton transactionReq_ui;
    // End of variables declaration//GEN-END:variables

    private double currencyconverter(double comm, String region) {
        if(region.equals("INDIA")){
            comm = comm/80.30;
        }
        else{
            comm = comm* 80.30;
        }
        return comm;
    }
}
