/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.java.ui;

import com.java.Faker.FakerClass;
import com.java.broker.Broker;
import com.java.broker.BrokerHandler;
import com.java.dbconn.DbConnectionBSE;
import com.java.dbconn.DbConnectionNSE;
import com.java.dbconn.DbConnectionNYSE;
import com.java.sebprofiles.SEBProfileClass;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import com.java.stocks.BSEClass;
import com.java.stocks.NSEClass;
import com.java.stocks.NYSEClass;
import java.awt.Color;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author rajmehta
 */
public class MainPanel extends javax.swing.JFrame {

    /**
     * Creates new form MainPanel
     */
    
    List<Integer> down = new ArrayList<>();
    Object[] aplStk = new Object[12]; 
    int loginId = 0;
    String loginName ="";
    String loginRegion = "";
    double loginFunds=0;
    String loginType="";
    BrokerHandler brokHandlerobj = new BrokerHandler();
    ArrayList<Broker> allBrokerList;
    String custRegion;
    FakerClass fakerobj;
    
    public MainPanel(){
        initComponents();
        
        loginPage_ui.setVisible(true);
        
        //run shell script that triggers pythonscript to fetch API data
        ProcessBuilder pb = new ProcessBuilder();
        pb.command("sh", "-c", "/Users/rajmehta/Desktop/StockBox/StockBoxApp/src/main/java/com/pythonscripts/runPythonScripts.sh");
        
        ExecutorService pool = Executors.newSingleThreadExecutor();
        try{
            Process process = pb.start();
            ProcessReader task = new ProcessReader(process.getInputStream());
            Future<List<String>> future = pool.submit(task);
            
            List<String> results = future.get();
            for(String res:results){
                System.out.println(res);
            }
            
            int exitcode = process.waitFor();
            System.out.println("ExitCode= "+exitcode);
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            pool.shutdown();
        }
        
//        try {
//            fakerobj = new FakerClass();
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
//        }

//AcceptIPO
//        try{
//            SEBProfileClass obj = new SEBProfileClass();
//            obj.approveIPO("AAPL", aplStk, "NYSE", 2000);
//        }catch(Exception e){e.printStackTrace();}
// 
//        //Reject IPO
//        try{
//            SEBProfileClass obj = new SEBProfileClass();
//            obj.rejectIPO("Apple");
//        }catch(Exception e){e.printStackTrace();}
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPage_ui = new javax.swing.JPanel();
        idLogin_ui = new javax.swing.JTextField();
        passLogin_ui = new javax.swing.JTextField();
        login_ui = new javax.swing.JButton();
        signin_ui = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        signinPage_ui = new javax.swing.JPanel();
        nameSignin_ui = new javax.swing.JTextField();
        passSignin_ui = new javax.swing.JTextField();
        regionSignin_ui = new javax.swing.JComboBox<>();
        typeSignin_ui = new javax.swing.JComboBox<>();
        signinSignin_ui = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        backSignin_ui = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        chooseBroker_ui = new javax.swing.JComboBox<>();
        loadBrokers = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        profileLink_ui = new javax.swing.JPanel();
        splitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        loginName_ui = new javax.swing.JTextField();
        proceedMain_ui = new javax.swing.JButton();
        profileMain_ui = new javax.swing.JPanel();
        moreLoginPages_ui = new javax.swing.JPanel();
        splitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        loginProfile_ui = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        loginPage_ui.setBackground(new java.awt.Color(43, 63, 87));
        loginPage_ui.setForeground(new java.awt.Color(255, 255, 255));
        loginPage_ui.setPreferredSize(new java.awt.Dimension(1440, 900));

        idLogin_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 24)); // NOI18N

        passLogin_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 24)); // NOI18N
        passLogin_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passLogin_uiActionPerformed(evt);
            }
        });

        login_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 24)); // NOI18N
        login_ui.setText("Sign In");
        login_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_uiActionPerformed(evt);
            }
        });

        signin_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 24)); // NOI18N
        signin_ui.setText("Sign Up");
        signin_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_uiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 2, 24)); // NOI18N
        jButton1.setText("More Login Options");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PROFILE LOGIN PAGE");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/MainBG.png"))); // NOI18N

        javax.swing.GroupLayout loginPage_uiLayout = new javax.swing.GroupLayout(loginPage_ui);
        loginPage_ui.setLayout(loginPage_uiLayout);
        loginPage_uiLayout.setHorizontalGroup(
            loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPage_uiLayout.createSequentialGroup()
                .addContainerGap(2349, Short.MAX_VALUE)
                .addGroup(loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPage_uiLayout.createSequentialGroup()
                        .addGroup(loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(loginPage_uiLayout.createSequentialGroup()
                                .addComponent(login_ui)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(signin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1)
                            .addGroup(loginPage_uiLayout.createSequentialGroup()
                                .addGroup(loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(12, 12, 12)
                                .addGroup(loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idLogin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passLogin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(524, 524, 524))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPage_uiLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 1415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        loginPage_uiLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {idLogin_ui, jButton1, login_ui, passLogin_ui, signin_ui});

        loginPage_uiLayout.setVerticalGroup(
            loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPage_uiLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLogin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLogin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(76, 76, 76)
                .addGroup(loginPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_ui)
                    .addComponent(signin_ui))
                .addGap(77, 77, 77)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(862, Short.MAX_VALUE))
        );

        loginPage_uiLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {idLogin_ui, jButton1, login_ui, passLogin_ui, signin_ui});

        getContentPane().add(loginPage_ui, "card2");

        signinPage_ui.setBackground(new java.awt.Color(43, 63, 87));

        nameSignin_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N

        passSignin_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N

        regionSignin_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        regionSignin_ui.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIA", "USA", "BOSTON" }));

        typeSignin_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        typeSignin_ui.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Business", "Investor" }));

        signinSignin_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        signinSignin_ui.setText("Sign Up");
        signinSignin_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinSignin_uiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Region:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Type:");

        backSignin_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        backSignin_ui.setText("Back");
        backSignin_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backSignin_uiActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Choose Broker:");

        chooseBroker_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        chooseBroker_ui.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        loadBrokers.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        loadBrokers.setText("Load Brokers in your region");
        loadBrokers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBrokersActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("PROFILE SIGN-UP PAGE");

        javax.swing.GroupLayout signinPage_uiLayout = new javax.swing.GroupLayout(signinPage_ui);
        signinPage_ui.setLayout(signinPage_uiLayout);
        signinPage_uiLayout.setHorizontalGroup(
            signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signinPage_uiLayout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signinPage_uiLayout.createSequentialGroup()
                        .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameSignin_ui)
                            .addComponent(passSignin_ui)
                            .addComponent(regionSignin_ui, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(typeSignin_ui, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chooseBroker_ui, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(loadBrokers, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signinPage_uiLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signinPage_uiLayout.createSequentialGroup()
                                .addGap(490, 490, 490)
                                .addComponent(backSignin_ui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signinPage_uiLayout.createSequentialGroup()
                                .addComponent(signinSignin_ui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(486, 486, 486)))))
                .addContainerGap())
            .addGroup(signinPage_uiLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(296, 296, 296))
        );
        signinPage_uiLayout.setVerticalGroup(
            signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signinPage_uiLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addGap(51, 51, 51)
                .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameSignin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passSignin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regionSignin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeSignin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(signinPage_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadBrokers)
                    .addComponent(chooseBroker_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(49, 49, 49)
                .addComponent(signinSignin_ui)
                .addGap(53, 53, 53)
                .addComponent(backSignin_ui, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(signinPage_ui, "card3");

        splitPane.setDividerLocation(100);
        splitPane.setDividerSize(8);

        jPanel1.setBackground(new java.awt.Color(43, 63, 87));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 459));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Welcome Back");

        loginName_ui.setEditable(false);

        proceedMain_ui.setText("Proceed");
        proceedMain_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedMain_uiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(loginName_ui, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(proceedMain_ui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginName_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(proceedMain_ui)
                .addContainerGap(1584, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(jPanel1);

        javax.swing.GroupLayout profileMain_uiLayout = new javax.swing.GroupLayout(profileMain_ui);
        profileMain_ui.setLayout(profileMain_uiLayout);
        profileMain_uiLayout.setHorizontalGroup(
            profileMain_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3650, Short.MAX_VALUE)
        );
        profileMain_uiLayout.setVerticalGroup(
            profileMain_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1776, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(profileMain_ui);

        javax.swing.GroupLayout profileLink_uiLayout = new javax.swing.GroupLayout(profileLink_ui);
        profileLink_ui.setLayout(profileLink_uiLayout);
        profileLink_uiLayout.setHorizontalGroup(
            profileLink_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileLink_uiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 3758, Short.MAX_VALUE)
                .addContainerGap())
        );
        profileLink_uiLayout.setVerticalGroup(
            profileLink_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        getContentPane().add(profileLink_ui, "card4");

        jPanel2.setBackground(new java.awt.Color(43, 63, 87));

        loginProfile_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        loginProfile_ui.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Broker", "SEB", "Company" }));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Login Profiles");

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(loginProfile_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addComponent(jLabel8))
                .addGap(0, 3647, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginProfile_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1544, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(14, 14, 14))
        );

        splitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1776, Short.MAX_VALUE)
        );

        splitPane1.setLeftComponent(jPanel3);

        javax.swing.GroupLayout moreLoginPages_uiLayout = new javax.swing.GroupLayout(moreLoginPages_ui);
        moreLoginPages_ui.setLayout(moreLoginPages_uiLayout);
        moreLoginPages_uiLayout.setHorizontalGroup(
            moreLoginPages_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane1)
        );
        moreLoginPages_uiLayout.setVerticalGroup(
            moreLoginPages_uiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane1)
        );

        getContentPane().add(moreLoginPages_ui, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passLogin_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passLogin_uiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passLogin_uiActionPerformed

    private void login_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_uiActionPerformed
        // TODO add your handling code here:
        try 
        {
            Connection con = null;
            PreparedStatement p = null;
            ResultSet rs = null;

            String url= "jdbc:mysql://127.0.0.1:3306/stockdb"; // table details 
            String username = "root"; // MySQL credentials
            String password = "root123$";

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url, username, password);

            if (con != null) 
            {
                System.out.println("Connected to the database StockDB");

                String sql = "Select * from profile where id="+Integer.parseInt(idLogin_ui.getText())+" AND password= '"+String.valueOf(passLogin_ui.getText())+"';";
                p = con.prepareStatement(sql);
                rs = p.executeQuery();
                
                boolean login = false;
                    while (rs.next()) 
                    {   
                            loginId = rs.getInt("id");
                            loginName =rs.getString("name");
                            loginRegion = rs.getString("region");
                            loginFunds = rs.getDouble("funds");
                            loginType = rs.getString("type");
                            
                            login = true;
                            JOptionPane.showMessageDialog(this,"Login successful for "+loginId+ " Name: "+loginName);  
                            loginPage_ui.setVisible(false);
                            profileLink_ui.setVisible(true);
                            loginName_ui.setText(loginName);
                            
                    }
                    
                    if(!login){JOptionPane.showMessageDialog(this,"Enter Valid details");}
 
            }
        } 
        catch (SQLException ex) 
        {
            // handle any errors
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_login_uiActionPerformed

    private void signin_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin_uiActionPerformed
        // TODO add your handling code here:
        loginPage_ui.setVisible(false);
        signinPage_ui.setVisible(true); 
    }//GEN-LAST:event_signin_uiActionPerformed

    private void signinSignin_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinSignin_uiActionPerformed
        // TODO add your handling code here:
        
        String fundsType = "";
        int id =0;
        if(String.valueOf(regionSignin_ui.getSelectedItem()).equals("INDIA")){fundsType = "INR";}
        else{fundsType = "USD";}

        try 
        {
            Connection con = null;
            PreparedStatement p = null;
            ResultSet rs = null;

            String url= "jdbc:mysql://127.0.0.1:3306/stockdb"; // table details 
            String username = "root"; // MySQL credentials
            String password = "root123$";

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url, username, password);

            if (con != null) 
            {
                System.out.println("Connected to the database StockDB");

                String sql = "INSERT INTO profile (name, funds, region, balance, type, password, fundstype) VALUES ('"+String.valueOf(nameSignin_ui.getText())+"',0,'"+String.valueOf(regionSignin_ui.getSelectedItem())+"',0,'"+String.valueOf(typeSignin_ui.getSelectedItem())+"','"+String.valueOf(passSignin_ui.getText())+"','"+fundsType+"');";

                p = con.prepareStatement(sql);
                int rowDeleted = p.executeUpdate(); 
                if(rowDeleted > 0){
                    String fetchId = "select * from profile where password = '" +String.valueOf(passSignin_ui.getText())+"' AND name = '"+String.valueOf(nameSignin_ui.getText())+"';";
                    p = con.prepareStatement(fetchId);
                    rs = p.executeQuery();

                    

                    while (rs.next()) 
                    {   
                            id = rs.getInt("id");
                    }
                        JOptionPane.showMessageDialog(this,"Account Created with id: "+id );  
                }
                
            }
        } 
        catch (SQLException ex) 
        {
            // handle any errors
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try{
            int brokerId = 0;
            String brokerName = String.valueOf(chooseBroker_ui.getSelectedItem());
            for(Broker b:allBrokerList){
                if(b.getName().equals(brokerName)){
                    brokerId = b.getBrokerid();
                }
            }
            brokHandlerobj.assignBrokertoProfile(id, brokerId);
        }catch(Exception e){e.printStackTrace();}
    }//GEN-LAST:event_signinSignin_uiActionPerformed

    private void backSignin_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backSignin_uiActionPerformed
        // TODO add your handling code here:
        signinPage_ui.setVisible(false);
        loginPage_ui.setVisible(true);
    }//GEN-LAST:event_backSignin_uiActionPerformed

    private void proceedMain_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedMain_uiActionPerformed
        // TODO add your handling code here:
        MainProfile mainProfileObj = new MainProfile(loginId, loginName, loginRegion, loginFunds, String.valueOf(passLogin_ui.getText()), loginType);
        splitPane.setRightComponent(mainProfileObj);
    }//GEN-LAST:event_proceedMain_uiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(String.valueOf(loginProfile_ui.getSelectedItem()).equals("Broker")){
            BrokerPanel bpObj = new BrokerPanel();
            splitPane1.setRightComponent(bpObj);
        }
        else if(String.valueOf(loginProfile_ui.getSelectedItem()).equals("Company")){
            CompanyPanel cpObj = new CompanyPanel();
            splitPane1.setRightComponent(cpObj);
        }
        else{
            SEBPanel sObj = new SEBPanel();
            splitPane1.setRightComponent(sObj);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        moreLoginPages_ui.setVisible(true);
        loginPage_ui.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loadBrokersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBrokersActionPerformed
        // TODO add your handling code here:
        custRegion = String.valueOf(regionSignin_ui.getSelectedItem());
        try{
            allBrokerList = brokHandlerobj.viewAllBrokerInfo(custRegion);
            chooseBroker_ui.removeAllItems();
            for(int i=0;i<allBrokerList.size();i++){
                chooseBroker_ui.addItem(String.valueOf(allBrokerList.get(i).getName()));
            }
        }catch(Exception e){e.printStackTrace();}
    }//GEN-LAST:event_loadBrokersActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        moreLoginPages_ui.setVisible(false);
        loginPage_ui.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPanel().setVisible(true);
            }
        });
    }
      
    public class MonCellRenderer extends DefaultTableCellRenderer {

        public Component getTableCellRendererComponent(JTable table, Object value,
                        boolean isSelected, boolean hasFocus, int row, int column) {
            super.getTableCellRendererComponent(table, value,
                            isSelected, hasFocus, row, column);

            if (down.contains(row)) {
                setBackground(Color.decode("#3d754e"));
            } else {
                setBackground(Color.decode("#bf0205"));
            }
            return this;
        }
        
}
    
    private static class ProcessReader implements Callable{
        private InputStream inputstream;
        
        public ProcessReader(InputStream is){
            this.inputstream=is;
        }
        
        @Override
        public Object call() throws Exception{
            return new BufferedReader(new InputStreamReader(inputstream)).lines().collect(Collectors.toList());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backSignin_ui;
    private javax.swing.JComboBox<String> chooseBroker_ui;
    private javax.swing.JTextField idLogin_ui;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loadBrokers;
    private javax.swing.JTextField loginName_ui;
    private javax.swing.JPanel loginPage_ui;
    private javax.swing.JComboBox<String> loginProfile_ui;
    private javax.swing.JButton login_ui;
    private javax.swing.JPanel moreLoginPages_ui;
    private javax.swing.JTextField nameSignin_ui;
    private javax.swing.JTextField passLogin_ui;
    private javax.swing.JTextField passSignin_ui;
    private javax.swing.JButton proceedMain_ui;
    private javax.swing.JPanel profileLink_ui;
    private javax.swing.JPanel profileMain_ui;
    private javax.swing.JComboBox<String> regionSignin_ui;
    private javax.swing.JPanel signinPage_ui;
    private javax.swing.JButton signinSignin_ui;
    private javax.swing.JButton signin_ui;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JSplitPane splitPane1;
    private javax.swing.JComboBox<String> typeSignin_ui;
    // End of variables declaration//GEN-END:variables
}
