/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.java.ui;

import Company.Company;
import Company.CompanyHandler;
import com.java.ipo.IPO;
import com.java.rules.RulesClass;
import com.java.sebprofiles.SEBProfileClass;
import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author aakashbhatt
 */
public class SEBPanel extends javax.swing.JPanel {

    /**
     * Creates new form SEBPanel
     */
    int id = 0;
    String pass = "";
    
    int loginid;
    String loginname;
    String loginboard;
    String loginregion;
    DefaultTableModel banUser;
    DefaultTableModel IpoTbl;
    
    public SEBPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        lbl = new javax.swing.JLabel();
        lblLoginId = new javax.swing.JLabel();
        txtId_ui = new javax.swing.JTextField();
        lblPwd = new javax.swing.JLabel();
        txtPwd_ui = new javax.swing.JTextField();
        btLogin = new javax.swing.JButton();
        back = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        lblSEB = new javax.swing.JLabel();
        btIPO = new javax.swing.JButton();
        btBan = new javax.swing.JButton();
        btBack = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        txtName_ui = new javax.swing.JTextField();
        lblRegion = new javax.swing.JLabel();
        txtRegion_ui = new javax.swing.JTextField();
        IPOPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbIPO_ui = new javax.swing.JTable();
        btApprove = new javax.swing.JButton();
        btReject = new javax.swing.JButton();
        btBacktoMain = new javax.swing.JButton();
        BanPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbBanUser = new javax.swing.JTable();
        btBanUser = new javax.swing.JButton();
        backbtn_ui = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        LoginPanel.setBackground(new java.awt.Color(43, 63, 87));

        lbl.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        lbl.setForeground(new java.awt.Color(255, 255, 255));
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setText("SEB Login");
        lbl.setAlignmentX(5.0F);
        lbl.setAlignmentY(5.0F);
        lbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblLoginId.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        lblLoginId.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginId.setText("Login ID :");
        lblLoginId.setAlignmentX(5.0F);
        lblLoginId.setAlignmentY(5.0F);

        txtId_ui.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        txtId_ui.setAlignmentX(5.0F);
        txtId_ui.setAlignmentY(5.0F);

        lblPwd.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        lblPwd.setForeground(new java.awt.Color(255, 255, 255));
        lblPwd.setText("Password :");
        lblPwd.setAlignmentX(5.0F);
        lblPwd.setAlignmentY(5.0F);

        txtPwd_ui.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        txtPwd_ui.setAlignmentX(5.0F);
        txtPwd_ui.setAlignmentY(5.0F);

        btLogin.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        btLogin.setText("Submit");
        btLogin.setAlignmentX(5.0F);
        btLogin.setAlignmentY(5.0F);
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(LoginPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LoginPanelLayout.createSequentialGroup()
                            .addGap(177, 177, 177)
                            .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblLoginId, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtId_ui, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                .addComponent(txtPwd_ui)))))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lbl)
                .addGap(18, 18, 18)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginId)
                    .addComponent(txtId_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPwd)
                    .addComponent(txtPwd_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(21, 21, 21))
        );

        add(LoginPanel, "card2");

        MainPanel.setBackground(new java.awt.Color(43, 63, 87));

        lblSEB.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        lblSEB.setForeground(new java.awt.Color(255, 255, 255));
        lblSEB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSEB.setText("STOCK EXCHANGE BOARD");

        btIPO.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        btIPO.setText("IPO APPROVE/REJECT");
        btIPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIPOActionPerformed(evt);
            }
        });

        btBan.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        btBan.setText("USER CONTROL");
        btBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBanActionPerformed(evt);
            }
        });

        btBack.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        btBack.setText("Back to Login");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("WELCOME BACK ");

        txtName_ui.setEditable(false);
        txtName_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        txtName_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName_uiActionPerformed(evt);
            }
        });

        lblRegion.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        lblRegion.setForeground(new java.awt.Color(255, 255, 255));
        lblRegion.setText("REGION :");

        txtRegion_ui.setEditable(false);
        txtRegion_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName_ui, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btIPO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(55, 55, 55)))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(lblRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRegion_ui, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(btBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(32, 32, 32)))
                .addGap(98, 98, 98))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(lblSEB, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btBack)
                .addGap(295, 295, 295))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblSEB, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtName_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtRegion_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIPO, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(btBan, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                .addGap(76, 76, 76)
                .addComponent(btBack)
                .addGap(25, 25, 25))
        );

        add(MainPanel, "card3");

        IPOPanel.setBackground(new java.awt.Color(43, 63, 87));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("IPO BOARD");

        tbIPO_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        tbIPO_ui.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Company Name", "Revenue", "Region", "Type", "ListingPrice", "Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbIPO_ui);

        btApprove.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        btApprove.setText("Approve");
        btApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApproveActionPerformed(evt);
            }
        });

        btReject.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        btReject.setText("Reject");
        btReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRejectActionPerformed(evt);
            }
        });

        btBacktoMain.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        btBacktoMain.setText("Back");
        btBacktoMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBacktoMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IPOPanelLayout = new javax.swing.GroupLayout(IPOPanel);
        IPOPanel.setLayout(IPOPanelLayout);
        IPOPanelLayout.setHorizontalGroup(
            IPOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IPOPanelLayout.createSequentialGroup()
                .addGroup(IPOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IPOPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IPOPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(btReject, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IPOPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(IPOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IPOPanelLayout.createSequentialGroup()
                        .addComponent(btBacktoMain)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IPOPanelLayout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))))
        );
        IPOPanelLayout.setVerticalGroup(
            IPOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IPOPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IPOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btApprove, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btReject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btBacktoMain)
                .addGap(20, 20, 20))
        );

        add(IPOPanel, "card4");

        BanPanel.setBackground(new java.awt.Color(43, 63, 87));
        BanPanel.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SUSPICIOUS CUSTOMERS/ INVESTORS / BUSINESS");

        tbBanUser.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        tbBanUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ProfileId", "Type", "Transactiontotal"
            }
        ));
        jScrollPane2.setViewportView(tbBanUser);

        btBanUser.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        btBanUser.setText("BAN USER");
        btBanUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBanUserActionPerformed(evt);
            }
        });

        backbtn_ui.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        backbtn_ui.setText("Back");
        backbtn_ui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn_uiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BanPanelLayout = new javax.swing.GroupLayout(BanPanel);
        BanPanel.setLayout(BanPanelLayout);
        BanPanelLayout.setHorizontalGroup(
            BanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BanPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(BanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbtn_ui))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(BanPanelLayout.createSequentialGroup()
                .addGroup(BanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BanPanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btBanUser, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BanPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );
        BanPanelLayout.setVerticalGroup(
            BanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btBanUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backbtn_ui)
                .addGap(14, 14, 14))
        );

        add(BanPanel, "card5");
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        // TODO add your handling code here:
                
      id = Integer.parseInt(txtId_ui.getText());
      pass = String.valueOf(txtPwd_ui.getText());
      
      try 
        {
            Connection con = null;
            PreparedStatement p = null;
            ResultSet rs = null;

            String url= "jdbc:mysql://127.0.0.1:3306/stockdb"; // table details 
            String username = "root"; // MySQL credentials
            String password = "root123$";

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url, username, password);

            if (con != null) 
            {
                System.out.println("Connected to the database StockDB");

                String sql = "Select * from SEBtable where id="+id+" AND name= '"+pass+"';";
                p = con.prepareStatement(sql);
                rs = p.executeQuery();
                
                boolean login = false;
                    while (rs.next()) 
                    {   
                            loginid = rs.getInt("id");
                            loginname= rs.getString("name");
                            loginboard = rs.getString("board");
                            loginregion= rs.getString("region");
                            
                            login = true;
                            JOptionPane.showMessageDialog(this,"Login successful for "+loginid+ " Name: "+loginname);  
                            LoginPanel.setVisible(false);
                            MainPanel.setVisible(true);
                            txtName_ui.setText(loginname);
                            txtRegion_ui.setText(loginregion);
                            
                    }
                    
                    if(!login){JOptionPane.showMessageDialog(this,"Enter Valid details");}
 
            }
        } 
        catch (SQLException ex) 
        {
            // handle any errors
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btLoginActionPerformed

    private void btBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBanActionPerformed
        // TODO add your handling code here:
        BanPanel.setVisible(true);
        MainPanel.setVisible(false);
        RulesClass robj = new RulesClass();
        try {
            banUser = (DefaultTableModel)tbBanUser.getModel();
            banUser.setRowCount(0);
            
            ArrayList<Integer> rulesInvalidate = robj.RulesValidation(loginregion);
            
            for(int u=0;u<rulesInvalidate.size();u++){
                System.out.println(rulesInvalidate.get(u));
                System.out.println("TT: "+robj.returnTransTotal(rulesInvalidate.get(u)));
                System.out.println("Type: "+robj.returnProfType(rulesInvalidate.get(u)));
                
                int i = rulesInvalidate.get(u);
                double t = robj.returnTransTotal(rulesInvalidate.get(u));
                String r = robj.returnProfType(rulesInvalidate.get(u));
                putProftoTable(i,t,r);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btBanActionPerformed

    private void btBacktoMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBacktoMainActionPerformed
        // TODO add your handling code here:
        MainPanel.setVisible(true);
        IPOPanel.setVisible(false);
    }//GEN-LAST:event_btBacktoMainActionPerformed

    private void btIPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIPOActionPerformed
        // TODO add your handling code here:
        IPOPanel.setVisible(true);
        MainPanel.setVisible(false);
        
        refreshIpoTable();
    }//GEN-LAST:event_btIPOActionPerformed

    private void backbtn_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn_uiActionPerformed
        // TODO add your handling code here:
        MainPanel.setVisible(true);
        BanPanel.setVisible(false);
    }//GEN-LAST:event_backbtn_uiActionPerformed

    private void btBanUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBanUserActionPerformed
        // TODO add your handling code here:
        banUser = (DefaultTableModel)tbBanUser.getModel();
        int selrow =tbBanUser.getSelectedRow();
        int banid = (Integer) banUser.getValueAt(selrow, 0);
        SEBProfileClass sobj = new SEBProfileClass();
        try {
            sobj.banUser(banid);
            refreshBanTable();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btBanUserActionPerformed

    private void btApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApproveActionPerformed
        // TODO add your handling code here:
        IpoTbl = (DefaultTableModel) tbIPO_ui.getModel();
        int selindex = tbIPO_ui.getSelectedRow();
        if(selindex>=0){
            String companyname=(String)IpoTbl.getValueAt(selindex, 0);
            double revenue= (Double)IpoTbl.getValueAt(selindex, 1); 
            String region= (String)IpoTbl.getValueAt(selindex, 2); 
            double listingprice= (Double)IpoTbl.getValueAt(selindex, 4); 
            int qty=(Integer)IpoTbl.getValueAt(selindex, 5);

            IPO iobj = new IPO();
            try {
                iobj.ApproveIPOReq(companyname, revenue, region, listingprice, qty);
                refreshIpoTable();
                JOptionPane.showMessageDialog(this, "Approved IPO and released Stock in "+region+" Market");
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        else{JOptionPane.showMessageDialog(this, "Please Select a row");
}
    }//GEN-LAST:event_btApproveActionPerformed

    private void btRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRejectActionPerformed
        // TODO add your handling code here:
        try{
            IPO iobj = new IPO();
            
            int selindex = tbIPO_ui.getSelectedRow();
            if(selindex>=0){
                String companyname=(String)IpoTbl.getValueAt(selindex, 0);
                iobj.RejectIPOReq(companyname);
                refreshIpoTable();
                JOptionPane.showMessageDialog(this, "Rejected IPO for "+companyname);
            }
            else{
                JOptionPane.showMessageDialog(this, "Please Select a row");
            }
        }catch(Exception e){e.printStackTrace();}
    }//GEN-LAST:event_btRejectActionPerformed

    private void txtName_uiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName_uiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName_uiActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        // TODO add your handling code here:
        MainPanel.setVisible(false);
        LoginPanel.setVisible(true);
    }//GEN-LAST:event_btBackActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        LoginPanel.setVisible(false);
        MainPanel back = new MainPanel();
        back.setVisible(true);
        
    }//GEN-LAST:event_backActionPerformed

    private void putProftoTable(int proid, double ttotal, String profType) {
        banUser = (DefaultTableModel)tbBanUser.getModel();
        Object row[]= new Object[3];
        row[0]= proid;
        row[1]= ttotal;
        row[2] = profType;
        banUser.addRow(row);      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BanPanel;
    private javax.swing.JPanel IPOPanel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton back;
    private javax.swing.JButton backbtn_ui;
    private javax.swing.JButton btApprove;
    private javax.swing.JButton btBack;
    private javax.swing.JButton btBacktoMain;
    private javax.swing.JButton btBan;
    private javax.swing.JButton btBanUser;
    private javax.swing.JButton btIPO;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblLoginId;
    private javax.swing.JLabel lblPwd;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblSEB;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tbBanUser;
    private javax.swing.JTable tbIPO_ui;
    private javax.swing.JTextField txtId_ui;
    private javax.swing.JTextField txtName_ui;
    private javax.swing.JTextField txtPwd_ui;
    private javax.swing.JTextField txtRegion_ui;
    // End of variables declaration//GEN-END:variables

    private void refreshBanTable() {
        RulesClass robj = new RulesClass();
        try {
            banUser = (DefaultTableModel)tbBanUser.getModel();
            banUser.setRowCount(0);
            
            ArrayList<Integer> rulesInvalidate = robj.RulesValidation(loginregion);
            
            for(int u=0;u<rulesInvalidate.size();u++){
                System.out.println(rulesInvalidate.get(u));
                System.out.println("TT: "+robj.returnTransTotal(rulesInvalidate.get(u)));
                System.out.println("Type: "+robj.returnProfType(rulesInvalidate.get(u)));
                
                int i = rulesInvalidate.get(u);
                double t = robj.returnTransTotal(rulesInvalidate.get(u));
                String r = robj.returnProfType(rulesInvalidate.get(u));
                putProftoTable(i,t,r);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void refreshIpoTable() {
        IpoTbl = (DefaultTableModel) tbIPO_ui.getModel();
        IpoTbl.setRowCount(0);
     
        CompanyHandler cobj = new CompanyHandler();
        
        try{
            Object[] row= new Object[6];
            ArrayList<Company> allCompanyList= cobj.viewAllCompanyInfo(loginregion);
            for(Company c:allCompanyList){
                row[0] = c.getCompanyname();
                row[1] = c.getRevenue();
                row[2] = c.getRegion();
                row[3] = c.getType();
                row[4] = c.getListingprice();
                row[5] = c.getQty();
                IpoTbl.addRow(row);
            }
        }
        catch(Exception e){e.printStackTrace();}
    }
}
